### ISSUE TITLE
JETSON XAVIER

### ISSUE THREAD

**Issue by jokerpoe** [GrgoMariani/NVidia-Jetson-DHT22-Python#4]
Can this library use with ds18b20 sensors? and is there any way to use it with python3?
Thank you

**Comment by GrgoMariani** [comment]
Hi, ds18b20 have the same OneWire protocol but i am sure it will not work for it without some modifications in the "C_DHT.c" file.

For python3 I see no limitation. Did you try to run the setup.py using python3 `(python3 setup.py install)`

**Comment by jokerpoe** [comment]
Thank you for your reply!
Yes, i tried _(python3 setup.py install)_  and face to Py_InitModule problem. Python3.6 doesn't not use this module and i modified it and run well.
But i still need to run it with ds18b20! Can you help me and give me some more detail information to modified it to fit with ds18b20?
I am a python coder so didn't know well.
**Very very thank you again**

**Comment by GrgoMariani** [comment]
Unfortunately this is not a ds18b20 project.
Also, i do not have neither the jetson board nor the mentioned sensor so I cannot test it at my place.

Maybe you should check some adafruit documentation about it and try from there.

**Comment by jokerpoe** [comment]
Thank you so much for your reply.
I will try it

**Comment by maldivien** [comment]
> Thank you for your reply!
> Yes, i tried _(python3 setup.py install)_ and face to Py_InitModule problem. Python3.6 doesn't not use this module and i modified it and run well.
> But i still need to run it with ds18b20! Can you help me and give me some more detail information to modified it to fit with ds18b20?
> I am a python coder so didn't know well.
> **Very very thank you again**

To build for python3 you can change the last 3 methods as follows.


`
```
static PyMethodDef module_methods[] = {
	{"readSensor", 		readSensor, 		METH_VARARGS, "Read all sensor values and return (float)temperature, (float)humidity and (0 or 1)message validity. If checksum not OK return -39909 (ERROR) as Humid and Temperature"},
	{"readSensorDHT11", readSensorDHT11, 	METH_VARARGS, "Read all sensor values and return (float)temperature, (float)humidity and (0 or 1)message validity. If checksum not OK return -39909 (ERROR) as Humid and Temperature. (Only for DHT11)"},
	{NULL, NULL, 0, NULL}
};

static struct PyModuleDef C_DHT =
{
    PyModuleDef_HEAD_INIT,
    "C_DHT", /* name of module */
    "usage: readSensor(PyObject *self, PyObject *args)\n", /* module documentation, may be NULL */
    -1,   /* size of per-interpreter state of the module, or -1 if the module keeps state in global variables. */
    module_methods,
	NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_C_DHT(void)
{
    return PyModule_Create(&C_DHT);
}
```

`
