### ISSUE TITLE
Getting same value for val1 and val2 in communicate( ) function.

### ISSUE THREAD

**Issue by Swapnil-gautam** [GrgoMariani/NVidia-Jetson-DHT22-Python#6]
I am using jetson nano 4gb, I have tested my gpio pin's with exampleGPIOAPP.cpp script and its working fine, I was able to get the input and output from the gpio pin's, but I am getting a constant high signal from DHT22 signal wire. The value in  byte0, byte1, byte2 and byte3 are also zero.

Thank you.

**Comment by GrgoMariani** [comment]
Are you sure your dht22 is working?

**Comment by Swapnil-gautam** [comment]
Thank you for replying.
Yes, the DHT22 sensor is working I have tested it with my Arduino UNO.
I have also tested the GPIO pins. 
The problem is in communication, I guess.

Thank you.

**Comment by GrgoMariani** [comment]
Well, for some reason your dht22 is not responding at all to the GPIO pin. I do not have the device with me so I cannot check what can be done.


I would suggest you to recheck your pins, or try the connecting it to other ones and recompiling the code.

Sometimes the source of the problem could be some minor thing such as not connecting 5V and GND.

If you think there is a problem with source code feel free to do a pull request.

**Comment by Swapnil-gautam** [comment]
No, sir, I am quite a newbi in programming so there is no point for pull request, and I have actually changed my sensor to BME280 which is working fine for me. 

Thank you
